### ISSUE TITLE
Get disconnected just after call within seconds in caller side.

### ISSUE THREAD

**Issue by hellosmith420** [sightcall/one-to-one-js-sample#2]
Hi,
Thanks for this nice project.
I have used caller and callee html files and placed the files in php server.
I have also configured the php token generation script.

But when I make the call I get the attached error.
![screen shot 2014-12-29 at 6 52 47 pm](https://cloud.githubusercontent.com/assets/10339654/5568926/6dbec00c-8f8c-11e4-8192-0137f393da61.png)

Here is my code I am only giving the lines, I have changed.:
## Callee : 
<script type="text/javascript" src="http://download.rtccloud.net/js/webappid/myappid"></script> 
AUTH_URL = 'http://x.x.x.x/dev/rtcc/gettoken.php?uid=001',
rtcc = new Rtcc('myappid', token, 'internal', options);

## Caller : 
<script type="text/javascript" src="http://download.rtccloud.net/js/webappid/myappid"></script> 
AUTH_URL = 'http://x.x.x.x/dev/rtcc/gettoken.php?uid=001',
rtcc = new Rtcc('myappid', token, 'internal', options);

## PHP

<?php
ini_set("display_errors", 0);

$RTCC_CACERT = "authCA.crt";
$RTCC_CLIENTP12 = "client.p12";

// $RTCC_CACERT = __DIR__.DIRECTORY_SEPARATOR."certs".DIRECTORY_SEPARATOR."authCA.crt";
// $RTCC_CLIENTP12 = __DIR__.DIRECTORY_SEPARATOR."certs".DIRECTORY_SEPARATOR."client.p12";

// Password
$RTCC_CERTPASSWORD = "xxxxxx";

// RTCC Auth endpoint, Client ID and Secret
$RTCC_AUTH_URL = "https://auth.rtccloud.net/auth/";
$RTCC_CLIENT_ID = "xxxxxxx";
$RTCC_CLIENT_SECRET = "xxxxxxxxxxxxxxxx";

// Include RTCC Auth Client File
require_once("./lib/RTCC_Auth_API_Client.php");
$uid = $_GET['uid'];
$identifier_client = "";
$id_profile = "standard";
error_log("Got UID: " . $uid);
try {
    $a = new RTCC_Client($RTCC_CACERT, $RTCC_CLIENT_ID, $RTCC_CLIENT_SECRET, $RTCC_CLIENTP12, $RTCC_CERTPASSWORD, $RTCC_AUTH_URL);
    $a->createKeyFile();
    $a->createCertFile();
    $a->initWCurl();
    $access_token = $a->sent($uid, $identifier_client, $id_profile);
    header('Access-Control-Allow-Origin: *');
    echo $access_token;
}
catch(Exception $e) {
    $message = $e->getMessage();
    error_log($message);
    header('Access-Control-Allow-Origin: *');
    echo "{ \"error\" : \Error\", \"error_description\" : \"".$message."\"}";
}
?>

**Comment by bsuhas86** [comment]
Thanks for demo app one to one.
I have run demo on latest chrome browsers sucessfully as mention changes done in code still I am unable to run other than latest chrome browser it will not supporing to Firefox ,IE. etc browsers.

Issue :  It will not ask for audio & video devices connected to machine by using Firefox/IE/Old chrome Browser.

It works only on Latest Chrome browser.

Please do need full help for browser compatiblity.

**Comment by RomainGabriel** [comment]
Hi bsuhas86,

We only support WebRTC using Google Chrome. We do provide a driver (Rtccdriver), which is a standalone app that provide the same features (and even more, such as screen sharing) for users on other web browsers (Firefox / Safari / IE).

If the web browser is not WebRTC-compatible, a pop-up should appear and prompt you to download this Rtccdriver.

I hope it helps!
Regards.
